# Dubbo配置
dubbo:
  application:
    name: boot-dubbo-service # 应用名
    qos-enable: false # 关闭在线调试
  registry:
    address: zookeeper://localhost:2181 # 注册中心地址
  protocol:
    name: dubbo # 协议名
    port: 20880 # 服务端口
  consumer:
    check: false
    timeout: 80000
   # mybatis-plus配置:
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml   # mapper xml扫包路径
  type-aliases-package: com.dj.yyds.entity   # pojo别名
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰映射
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   # 打印SQL日志

spring:
  datasource: # 数据库配置
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: '000000'
    url: jdbc:mysql://localhost:3306/mybatis_plus?useSSL=false&serverTimezone=GMT%2B8
logging:
  level:
    com.dj.yyds.mapper: debug # 打印mapper级别的debug日志

